### ISSUE TITLE
No Texture

### ISSUE THREAD

**Issue by div64x** [jojos38/lamborghini-gallardo-improved#1]
The cars has no textures

**Comment by jojos38** [comment]
Hi, please do this:
If you have any issue with a new update delete those two folders before starting your game:
C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\temp\vehicles\gallardo
C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\vehicles\gallardo

**Comment by div64x** [comment]
i dont find any of these folders

**Comment by jojos38** [comment]
They are located in your game's documents folder (the one which contains the mods folder etc)

**Comment by div64x** [comment]
i found it

**Comment by div64x** [comment]
should i delete gallardo om vehicles?

**Comment by jojos38** [comment]
You should only keep my gallardo version, don't keep any other version and make sure to delete the folders I said above, in your game's documents folder

**Comment by div64x** [comment]
oh it worked thanks

**Comment by jojos38** [comment]
No prob, have fun!
