### ISSUE TITLE
Problems With Textures

### ISSUE THREAD

**Issue by 101Corp** [jojos38/lamborghini-gallardo-improved#2]
I have a problem with textures.
The car would load, but either it has a white body, it has a transparent colored body, or it has no body.
Often, the car's lights and rims would be chrome.
Other than that, the car works fine.
I need help.
I could not find the temp files for the Gallardo, in documents or anywhere else.
Do I have to delete them while the game is running?
Again, I need help.

**Comment by jojos38** [comment]
Hey, please follow this:

If you have any issue with the mod delete those two folders before starting your game:
C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\temp\vehicles\gallardo
C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\vehicles\gallardo

This is where the temp files are located
The game should be closed when deleting them

**Comment by 101Corp** [comment]
> Hey, please follow this:
> 
> If you have any issue with the mod delete those two folders before starting your game:
> C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\temp\vehicles\gallardo
> C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\vehicles\gallardo
> 
> This is where the temp files are located
> The game should be closed when deleting them

It just says it doesn't exist

**Comment by jojos38** [comment]
> > Hey, please follow this:
> > If you have any issue with the mod delete those two folders before starting your game:
> > C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\temp\vehicles\gallardo
> > C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\vehicles\gallardo
> > This is where the temp files are located
> > The game should be closed when deleting them
> 
> It just says it doesn't exist

They are located in your game's user folder, it is in the same location where the mods folder is

**Comment by 101Corp** [comment]
> > > Hey, please follow this:
> > > If you have any issue with the mod delete those two folders before starting your game:
> > > C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\temp\vehicles\gallardo
> > > C:\Users\YOUR_USERNAME\AppData\Local\BeamNG.drive\latest\vehicles\gallardo
> > > This is where the temp files are located
> > > The game should be closed when deleting them
> > 
> > 
> > It just says it doesn't exist
> 
> They are located in your game's user folder, it is in the same location where the mods folder is

here
C:\Users\My User\OneDrive\Documents\BeamNG.drive
?
I tried there too
Still doesn't exist

**Comment by jojos38** [comment]
Where did you put the mod? In the documents/BeamNG.drive folder?
If so in this same folder (documents/BeamNG.drive) you should find the two folders called "vehicles" and "temp"
If you don't I honestly have no idea, do you have the latest version of the game?

**Comment by 101Corp** [comment]
> Where did you put the mod? In the documents/BeamNG.drive folder?
> If so in this same folder (documents/BeamNG.drive) you should find the two folders called "vehicles" and "temp"
> If you don't I honestly have no idea, do you have the latest version of the game?

documents/BeamNG.drive/mods
There is no "temp" in BeamNG.drive
And i cant install the latest version, im having issues doing so, i bet thats why

**Comment by jojos38** [comment]
Yeah you need the latest version this is why it doesn't have the temp folder

**Comment by 101Corp** [comment]
> Yeah you need the latest version this is why it doesn't have the temp folder

Ok thx

**Comment by jojos38** [comment]
No prob

**Comment by 101Corp** [comment]
Ok i know you closed this but i figured out the issue and the game is now downloading.
Thanks for your help
However, how do I make the game download faster? It only downloads at 280kb/ps and I have good internet. Is it just that Steam downloads slow, or my computer is having problems?
