### ISSUE TITLE
The oilpan

### ISSUE THREAD

**Issue by 101Corp** [jojos38/lamborghini-gallardo-improved#3]
Is the oil pan supposed to be so flimsy?
BTW i fixed the textures with the update

**Comment by jojos38** [comment]
Hey, thanks for the report, yeah it's on the "known issues" list, I don't understand about the texture though?

**Comment by 101Corp** [comment]
> Hey, thanks for the report, yeah it's on the "known issues" list, I don't understand about the texture though?

I updated my game and fixed the textures

**Comment by jojos38** [comment]
> > Hey, thanks for the report, yeah it's on the "known issues" list, I don't understand about the texture though?
> 
> I updated my game and fixed the textures

oooh, that's sick! Do you want me to add it to the mod and credit you? If so you can use pull request from Github or send the files to me
