### ISSUE TITLE
Will you include rims and front/rear bumpers from all 3 generations of Gallardo?

### ISSUE THREAD

**Issue by Derpitron** [jojos38/lamborghini-gallardo-improved#5]
### Front
![image](https://user-images.githubusercontent.com/46134462/132248089-c1dbc216-67e1-4e4f-9c4a-6364d2fb05bd.png)
### Rear
![image](https://user-images.githubusercontent.com/46134462/132248160-7f9c2bd1-f8fd-46ea-a556-c9cfff04b366.png)

### Front
![image](https://user-images.githubusercontent.com/46134462/132248282-59607009-5cf8-49ee-9f5e-7c6144379175.png)
### Rear
![image](https://user-images.githubusercontent.com/46134462/132248291-bd0e4c26-f2b7-4879-a375-6a0f31c9d120.png)

## Rims
I have found a web page which helpfully lists all the Lamborghini Gallardo stock wheel options 
http://edbolian.com/all-of-the-lamborghini-gallardo-factory-wheel-options/

**Comment by jojos38** [comment]
Hey! The issue is not about including or not including is that I need to find the 3D files for them, it's hard to find good qualitry 3d models that are free

**Comment by Derpitron** [comment]
hey Ok thanks for the clarification
